version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: cpanel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-cpanel}
      MYSQL_USER: ${DB_USERNAME:-cpanel_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-cpanel_password}
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cpanel-network
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-connect=SET NAMES utf8mb4

  # 主应用服务
  cpanel-app:
    image: c0w0c/cpanel-app:latest
    container_name: cpanel-app
    restart: unless-stopped
    environment:
      # 数据库配置
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-cpanel}
      DB_USERNAME: ${DB_USERNAME:-cpanel_user}
      DB_PASSWORD: ${DB_PASSWORD:-cpanel_password}

      # JWT配置
      JWT_SECRET: ${JWT_SECRET:-cpanel-jwt-secret-key-for-authentication-system-2024-very-long-secret-docker}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-604800000}
      JWT_ISSUER: ${JWT_ISSUER:-cpanel}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-cpanel-users}

      # 应用配置
      SPRING_PROFILES_ACTIVE: docker
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      TZ: Asia/Shanghai

      # JVM配置
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8081:8080"
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    networks:
      - cpanel-network
    depends_on:
      - mysql

# 网络配置
networks:
  cpanel-network:
    driver: bridge

# 数据卷配置
volumes:
  mysql_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
